// Cloud-Native artifact categories — Digital Forensics Reference
// See artifacts/windows.js header for how to add/edit/remove entries.
// NOTE: Cloud forensics differs from endpoint forensics in a key way — most of
// these "artifacts" are logs and configuration state living in the cloud provider's
// own control plane, not files on a disk you image. Access typically requires
// account-level API/console permissions rather than physical/local access.
export const CloudNative = {
  "AWS": [
    { artifact: "CloudTrail Logs", locations: ["S3 bucket configured as CloudTrail destination", "AWS Console: CloudTrail > Event history"], tools: ["AWS CLI", "CloudTrail Lake", "Athena queries on S3", "Splunk/SIEM ingestion"], reveals: "Every API call made against the AWS account — who (IAM user/role), what action, source IP, timestamp, request parameters, response. The foundational audit log for any AWS incident.", eventIds: [], mitre: ["T1078.004", "T1562.008"], commands: [{ label: "Look up recent events for a user via CLI", cmd: "aws cloudtrail lookup-events --lookup-attributes AttributeKey=Username,AttributeValue=[user]" }], related: ["IAM Access Analyzer Findings", "GuardDuty Findings"], retention: "Default CloudTrail event history via console covers 90 days; for longer retention, trails must be explicitly configured to deliver to S3, which then follows the bucket's own lifecycle policy (commonly kept much longer).", sources: ["AWS CloudTrail documentation"] },
    { artifact: "VPC Flow Logs", locations: ["CloudWatch Logs group or S3 bucket, as configured per VPC/subnet/ENI"], tools: ["AWS CLI", "CloudWatch Logs Insights", "Athena", "SIEM ingestion"], reveals: "Network flow metadata (not packet content) for traffic in/out of a VPC — source/dest IP and port, protocol, bytes, accept/reject action. Key for detecting C2 beaconing, port scanning, data exfiltration volume.", eventIds: [], mitre: ["T1071", "T1041"], commands: [{ label: "Query flow logs via CloudWatch Insights (example filter)", cmd: "fields @timestamp, srcAddr, dstAddr, action | filter action = \"REJECT\"" }], related: ["CloudTrail Logs", "Security Group Configuration History"], retention: "Must be explicitly enabled per VPC/subnet/ENI (disabled by default) — if not turned on before the incident, no historical flow data exists regardless of investigation urgency.", sources: ["AWS VPC Flow Logs documentation"] },
    { artifact: "IAM Access Analyzer Findings", locations: ["AWS Console: IAM > Access Analyzer"], tools: ["AWS CLI", "AWS Console"], reveals: "Resources shared with external entities, overly permissive policies, unused access — useful for identifying misconfigurations that enabled unauthorized access.", eventIds: [], mitre: ["T1078.004"], commands: [], related: ["CloudTrail Logs"], retention: "Findings reflect current configuration state at time of analysis, not historical changes — pair with CloudTrail for the change history that led to a finding.", sources: ["AWS IAM Access Analyzer documentation"] },
    { artifact: "GuardDuty Findings", locations: ["AWS Console: GuardDuty > Findings"], tools: ["AWS CLI", "AWS Console", "SIEM integration via EventBridge"], reveals: "Automated threat detection findings — compromised credentials, cryptomining, unusual API call patterns, known-malicious IP communication. A managed detection layer on top of CloudTrail/VPC Flow Logs/DNS logs.", eventIds: [], mitre: ["T1496", "T1078.004"], commands: [{ label: "List findings via CLI", cmd: "aws guardduty list-findings --detector-id [detector-id]" }], related: ["CloudTrail Logs", "VPC Flow Logs"], retention: "Findings are retained per GuardDuty's own retention policy (commonly 90 days by default in the console) — export to S3/SIEM for longer-term retention.", sources: ["AWS GuardDuty documentation"] },
    { artifact: "S3 Access Logs / Server Access Logging", locations: ["Destination S3 bucket configured for access log delivery"], tools: ["AWS CLI", "Athena queries", "Text-based log review"], reveals: "Per-request access logs for an S3 bucket — requester, bucket, key, operation, response, bytes transferred. Key for investigating unauthorized data access or bulk download/exfiltration from a bucket.", eventIds: [], mitre: ["T1530", "T1567.002"], commands: [], related: ["CloudTrail Logs"], retention: "Must be explicitly enabled per bucket (disabled by default) — like Flow Logs, no historical data exists if not turned on beforehand.", sources: ["AWS S3 Server Access Logging documentation"] },
    { artifact: "Security Group Configuration History", locations: ["AWS Config (if enabled) — Config > Resource history", "CloudTrail events for ec2:AuthorizeSecurityGroupIngress etc."], tools: ["AWS Config", "AWS CLI", "CloudTrail"], reveals: "Changes to network security group rules over time — who opened a port, when, and what the rule allowed. Critical for identifying how an attacker widened network access.", eventIds: [], mitre: ["T1562.007"], commands: [], related: ["VPC Flow Logs", "CloudTrail Logs"], retention: "Requires AWS Config to be enabled beforehand for full historical resource state; CloudTrail alone shows the change events but not point-in-time resource snapshots.", sources: ["AWS Config documentation"] },
    { artifact: "Lambda Function Execution Logs", locations: ["CloudWatch Logs group /aws/lambda/[function-name]"], tools: ["AWS CLI", "CloudWatch Logs Insights"], reveals: "Serverless function invocation logs — useful when a compromised or malicious Lambda function is part of the attack chain (e.g., used for persistence or data processing).", eventIds: [], mitre: ["T1610"], commands: [{ label: "Tail Lambda logs via CLI", cmd: "aws logs tail /aws/lambda/[function-name] --follow" }], related: ["CloudTrail Logs"], retention: "Log retention period is configurable per log group (default is indefinite unless explicitly set) — check the specific log group's retention setting.", sources: ["AWS Lambda documentation"] },
  ],
  "Azure": [
    { artifact: "Azure Activity Log", locations: ["Azure Portal: Monitor > Activity Log", "exportable to Log Analytics workspace"], tools: ["Azure CLI", "Azure Portal", "Log Analytics KQL queries"], reveals: "Subscription-level control-plane operations — resource creation/deletion/modification, who performed the action, timestamp, source. The Azure equivalent of AWS CloudTrail.", eventIds: [], mitre: ["T1078.004"], commands: [{ label: "Query activity log via Azure CLI", cmd: "az monitor activity-log list --resource-group [rg-name]" }], related: ["Azure AD Sign-In Logs"], retention: "Default retention in the Activity Log is 90 days; for longer retention, must be routed to a Log Analytics workspace or storage account.", sources: ["Microsoft Learn — Azure Activity Log"] },
    { artifact: "Azure AD Sign-In Logs", locations: ["Azure Portal: Azure AD > Sign-in logs", "Microsoft Entra admin center"], tools: ["Azure CLI", "Microsoft Graph API", "Azure Portal"], reveals: "Authentication events against Azure AD/Entra ID — user, application, source IP, device, conditional access result, MFA status. Critical for identifying compromised accounts and impossible-travel scenarios.", eventIds: [], mitre: ["T1078.004", "T1110"], commands: [{ label: "Query sign-ins via Microsoft Graph (PowerShell)", cmd: "Get-MgAuditLogSignIn -Filter \"userPrincipalName eq '[user]'\"" }], related: ["Azure Activity Log", "Conditional Access Policy Changes"], retention: "Free Azure AD tier retains 7 days; Premium (P1/P2) tiers retain 30 days by default — export to a Log Analytics workspace for longer historical retention.", sources: ["Microsoft Learn — Azure AD Sign-In Logs"] },
    { artifact: "Azure Storage Account Logs", locations: ["Configured Log Analytics workspace or storage account $logs container"], tools: ["Azure CLI", "Log Analytics KQL queries"], reveals: "Per-request access logs for Blob/File/Queue/Table storage — similar forensic value to AWS S3 access logs, useful for data exfiltration investigations.", eventIds: [], mitre: ["T1530", "T1567.002"], commands: [], related: ["Azure Activity Log"], retention: "Must be explicitly enabled per storage account — not on by default.", sources: ["Microsoft Learn — Azure Storage Analytics Logging"] },
    { artifact: "Network Security Group (NSG) Flow Logs", locations: ["Configured storage account destination, via Azure Network Watcher"], tools: ["Azure CLI", "Azure Network Watcher", "Traffic Analytics (Log Analytics)"], reveals: "Network flow metadata for traffic through an NSG — source/dest IP and port, protocol, allow/deny decision. Azure's equivalent of AWS VPC Flow Logs.", eventIds: [], mitre: ["T1071", "T1041"], commands: [], related: ["Azure Storage Account Logs"], retention: "Requires Network Watcher and flow logging to be explicitly enabled per NSG — disabled by default.", sources: ["Microsoft Learn — NSG Flow Logs"] },
    { artifact: "Conditional Access Policy Changes", locations: ["Azure AD > Audit logs (filtered to policy category)"], tools: ["Azure Portal", "Microsoft Graph API"], reveals: "Changes to Conditional Access policies — an attacker with sufficient privilege may weaken MFA/location-based restrictions as part of an intrusion; this log shows exactly what changed and by whom.", eventIds: [], mitre: ["T1556.006"], commands: [], related: ["Azure AD Sign-In Logs"], retention: "Same tiered retention as other Azure AD audit logs — 7 days free tier, 30 days Premium, longer if exported to Log Analytics.", sources: ["Microsoft Learn — Azure AD Audit Logs"] },
  ],
  "Google Cloud Platform": [
    { artifact: "Cloud Audit Logs (Admin Activity)", locations: ["Google Cloud Console: Logging > Logs Explorer", "exportable to BigQuery/Cloud Storage/Pub/Sub"], tools: ["gcloud CLI", "Cloud Logging API", "BigQuery SQL"], reveals: "Administrative actions across GCP resources — who changed what, when, from where. GCP's equivalent of CloudTrail/Azure Activity Log; Admin Activity logs are always on and cannot be disabled.", eventIds: [], mitre: ["T1078.004"], commands: [{ label: "Query recent audit logs via gcloud", cmd: "gcloud logging read \"logName:cloudaudit.googleapis.com\" --limit 50" }], related: ["Cloud Audit Logs (Data Access)", "IAM Policy Change History"], retention: "Admin Activity audit logs are retained for 400 days by default in Cloud Logging — among the longest default retentions of the major cloud providers.", sources: ["Google Cloud Audit Logs documentation"] },
    { artifact: "Cloud Audit Logs (Data Access)", locations: ["Google Cloud Console: Logging > Logs Explorer (Data Access category)"], tools: ["gcloud CLI", "Cloud Logging API", "BigQuery SQL"], reveals: "Read/write access to user data within GCP services (e.g., who read which object in a Cloud Storage bucket) — must be explicitly enabled per service, unlike Admin Activity logs.", eventIds: [], mitre: ["T1530", "T1567.002"], commands: [], related: ["Cloud Audit Logs (Admin Activity)"], retention: "Default retention is 30 days unless explicitly enabled and routed to a longer-retention sink — Data Access logging itself must be turned on per-service beforehand.", sources: ["Google Cloud Audit Logs documentation"] },
    { artifact: "VPC Flow Logs (GCP)", locations: ["Configured per-subnet, delivered to Cloud Logging or BigQuery"], tools: ["gcloud CLI", "Cloud Logging", "BigQuery SQL"], reveals: "Network flow metadata for a VPC subnet — same forensic value as AWS/Azure flow logs. Must be explicitly enabled per subnet.", eventIds: [], mitre: ["T1071", "T1041"], commands: [], related: ["Cloud Audit Logs (Admin Activity)"], retention: "Must be explicitly enabled per subnet (disabled by default); once enabled, retention follows the configured Cloud Logging sink's own retention policy.", sources: ["Google Cloud VPC Flow Logs documentation"] },
    { artifact: "IAM Policy Change History", locations: ["Cloud Asset Inventory — asset history API", "Admin Activity audit logs (SetIamPolicy events)"], tools: ["gcloud CLI (asset feeds)", "Cloud Asset Inventory API"], reveals: "Historical changes to IAM bindings on a resource — who was granted/revoked what role, when. Key for identifying privilege escalation during an incident.", eventIds: [], mitre: ["T1098.001"], commands: [{ label: "Query IAM policy history via gcloud", cmd: "gcloud asset search-all-iam-policies --scope=projects/[project-id]" }], related: ["Cloud Audit Logs (Admin Activity)"], retention: "Cloud Asset Inventory retains historical asset state for 35 days by default via the API; Admin Activity logs recording the same events are retained 400 days.", sources: ["Google Cloud Asset Inventory documentation"] },
  ],
};
