// iOS artifact categories — Digital Forensics Reference
// See artifacts/windows.js header for how to add/edit/remove entries.
// NOTE: iOS forensics differs sharply by acquisition type — most artifacts here
// require either a checkm8-based (bootrom-exploit) full filesystem extraction,
// a jailbroken device, or an iTunes/Finder-style encrypted backup. Where relevant,
// the "locations" field reflects paths inside a full filesystem extraction, not
// what's accessible from a normal logical (backup-only) acquisition.
export const iOS = {
  Authentication: [
    { artifact: "Keychain Database", locations: ["private/var/Keychains/keychain-2.db"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "iOS Keychain Dumper (jailbroken)"], reveals: "Saved passwords, Wi-Fi PSKs, app tokens, certificates — protected by class keys tied to the device passcode; a full filesystem extraction plus the device passcode (or a bypass) is typically required to decrypt.", eventIds: [], mitre: ["T1555"], commands: [], related: ["Lockdown Certificates & Pairing Records"], retention: "Persists until the app/account is removed or the user resets the device — durable across normal use.", sources: ["Apple Platform Security documentation"] },
    { artifact: "Lockdown Certificates & Pairing Records", locations: ["/private/var/db/lockdown/", "macOS: ~/Library/Lockdown/"], tools: ["libimobiledevice", "Cellebrite", "AXIOM"], reveals: "Pairing records from computers the device has trusted — proves which machines had trusted USB/Wi-Fi sync access, useful for establishing device-computer relationships.", eventIds: [], mitre: ["T1550"], commands: [{ label: "List paired lockdown records (macOS host)", cmd: "ls ~/Library/Lockdown/" }], related: ["Keychain Database"], retention: "Persists until the user revokes trust for that computer in Settings — no automatic expiry.", sources: ["libimobiledevice project documentation"] },
    { artifact: "Face ID / Touch ID Enrollment Metadata", locations: ["Secure Enclave — not extractable via software"], tools: ["Not extractable through standard forensic tooling"], reveals: "Only enrollment count/timestamp metadata may be visible in system logs; the biometric template itself is hardware-isolated in the Secure Enclave and not accessible.", eventIds: [], mitre: [], commands: [], related: ["Keychain Database"], retention: "Enrollment metadata persists until the biometric is removed in Settings; underlying template security is independent of software retention.", sources: ["Apple Platform Security documentation"] },
  ],
  "File Activity": [
    { artifact: "Full Filesystem Extraction Layout", locations: ["/private/var/mobile/ (user data)", "/private/var/mobile/Media/ (photos, downloads)"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "checkm8-based extraction tools"], reveals: "Complete on-device filesystem when a full (physical/checkm8) extraction is possible — app sandboxes, shared media, system logs. Only obtainable on devices vulnerable to a bootrom exploit or already jailbroken.", eventIds: [], mitre: ["T1005"], commands: [], related: ["App Sandbox Containers"], retention: "Reflects the device state at time of extraction — no separate retention concept beyond normal file lifecycle.", sources: ["Apple File System (APFS) documentation"] },
    { artifact: "App Sandbox Containers", locations: ["/private/var/mobile/Containers/Data/Application/[UUID]/"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM"], reveals: "Per-app sandboxed data — SQLite databases, plists, cached files — analogous to Android's /data/data/[package]/ structure. Each app's UUID container must be individually enumerated.", eventIds: [], mitre: ["T1005"], commands: [], related: ["Full Filesystem Extraction Layout"], retention: "Persists until the app is deleted; sandbox is destroyed with the app on uninstall.", sources: ["Apple App Sandbox documentation"] },
    { artifact: "KnowledgeC Database", locations: ["/private/var/mobile/Library/CoreDuet/Knowledge/knowledgeC.db"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "APOLLO (open-source)", "sqlite3"], reveals: "Extremely rich device usage timeline — app foreground/background events, screen on/off, plugged-in state, notifications, even some third-party app usage. Considered one of the most valuable iOS artifacts.", eventIds: [], mitre: ["T1217"], commands: [{ label: "Query recent app usage entries", cmd: 'sqlite3 knowledgeC.db "SELECT ZOBJECT.ZVALUESTRING, ZOBJECT.ZSTARTDATE FROM ZOBJECT ORDER BY ZSTARTDATE DESC LIMIT 50"' }], related: ["App Sandbox Containers"], retention: "Typically retains several weeks to months of history depending on device storage and usage volume.", sources: ["APOLLO (Apple Pattern of Life Lazy Output'er) project documentation"] },
    { artifact: "Photos.sqlite (Photos Library)", locations: ["/private/var/mobile/Media/PhotoData/Photos.sqlite"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "sqlite3"], reveals: "Full photo/video metadata — GPS, timestamps, albums, hidden/deleted status, Live Photo pairing, associated Depth/Portrait data.", eventIds: [], mitre: ["T1005"], commands: [], related: ["Full Filesystem Extraction Layout"], retention: "Recently deleted photos are retained in a 'Recently Deleted' album for 30 days before permanent removal.", sources: ["Apple Photos framework documentation"] },
  ],
  "Browsing Activity": [
    { artifact: "Safari History & Favicon Cache", locations: ["/private/var/mobile/Library/Safari/History.db", "/private/var/mobile/Library/Safari/Favicon Cache/"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "sqlite3"], reveals: "Full mobile Safari browsing history, favicon cache (can reveal visited domains even after history deletion in some cases).", eventIds: [], mitre: ["T1217"], commands: [], related: ["KnowledgeC Database"], retention: "Default retention roughly mirrors desktop Safari — recent months of history unless manually cleared.", sources: ["Apple Safari documentation"] },
    { artifact: "Safari Tabs (Persisted State)", locations: ["/private/var/mobile/Containers/Data/Application/[Safari UUID]/Library/Safari/BrowserState.db"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM"], reveals: "Currently open Safari tabs including private tabs' URLs at time of extraction — private browsing tabs do not persist history but their open-tab state can still be captured live.", eventIds: [], mitre: ["T1217"], commands: [], related: ["Safari History & Favicon Cache"], retention: "Reflects only the live/current tab state — closing a tab or restarting Safari changes this immediately.", sources: ["Apple Safari documentation"] },
  ],
  "Network Activity": [
    { artifact: "Wi-Fi Known Networks (com.apple.wifi.plist)", locations: ["/private/var/preferences/SystemConfiguration/com.apple.wifi.plist"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "plutil"], reveals: "All Wi-Fi networks ever joined — SSID, BSSID, last-joined timestamp, security type. Same forensic value as Android's WifiConfigStore.", eventIds: [], mitre: ["T1016"], commands: [], related: ["Cell Tower Connection History"], retention: "Persists until the user manually forgets the network.", sources: ["Apple Configuration Profile Reference"] },
    { artifact: "Cell Tower Connection History", locations: ["/private/var/wireless/Library/Databases/CellularUsage.db"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM"], reveals: "Cell tower connection records — useful for coarse location/timeline corroboration alongside GPS artifacts.", eventIds: [], mitre: ["T1430"], commands: [], related: ["Wi-Fi Known Networks (com.apple.wifi.plist)"], retention: "Retention varies by carrier profile and device configuration — generally covers recent weeks to months.", sources: ["Apple cellular documentation"] },
  ],
  "Call & Messaging": [
    { artifact: "iMessage / SMS Database (sms.db)", locations: ["/private/var/mobile/Library/SMS/sms.db"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "iExplorer", "sqlite3"], reveals: "iMessage and SMS/MMS conversations — sender, recipient, body, timestamps, read receipts, attachments, group chat membership.", eventIds: [], mitre: ["T1636.002"], commands: [{ label: "Query recent messages", cmd: 'sqlite3 sms.db "SELECT text, date FROM message ORDER BY date DESC LIMIT 50"' }], related: ["Call History Database"], retention: "Persists indefinitely by default unless the user enables auto-delete (30 days/1 year) in Messages settings.", sources: ["Apple Messages documentation"] },
    { artifact: "Call History Database", locations: ["/private/var/mobile/Library/CallHistoryDB/CallHistory.storedata"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "sqlite3"], reveals: "Call log — number, duration, timestamp, call type (cellular/FaceTime audio/FaceTime video), answered/missed status.", eventIds: [], mitre: [], commands: [], related: ["iMessage / SMS Database (sms.db)"], retention: "Persists indefinitely unless manually cleared by the user.", sources: ["Apple Messages documentation"] },
    { artifact: "WhatsApp on iOS", locations: ["/private/var/mobile/Containers/Shared/AppGroup/[UUID]/ChatStorage.sqlite"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "WhatsApp Viewer"], reveals: "Same forensic value as Android WhatsApp — messages, media, contacts — stored in a shared App Group container rather than the app's own sandbox.", eventIds: [], mitre: ["T1636.002"], commands: [], related: ["iMessage / SMS Database (sms.db)"], retention: "Daily encrypted local backups (ChatStorage.sqlite.crypt14-style) provide a rolling window of recent history even if the live database is cleared.", sources: ["WhatsApp encryption documentation"] },
  ],
  "Location Data": [
    { artifact: "Significant Locations Cache", locations: ["/private/var/mobile/Library/Caches/com.apple.routined/Cache.sqlite"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "iLEAPP (open-source)"], reveals: "Apple's 'Significant Locations' feature — clusters of GPS points representing places the user frequently visits, with arrival/departure timestamps. One of the richest location artifacts on iOS.", eventIds: [], mitre: ["T1430"], commands: [], related: ["Photos.sqlite (Photos Library)"], retention: "Rolling window, typically retaining recent months of significant-location clusters; older, less-visited locations are pruned over time.", sources: ["iLEAPP project documentation"] },
    { artifact: "Photos GPS/EXIF Metadata", locations: ["Embedded in each photo asset; indexed in Photos.sqlite"], tools: ["ExifTool", "Cellebrite Physical Analyzer", "Magnet AXIOM"], reveals: "Same as Android — precise GPS coordinates and timestamp embedded per photo/video, unless Location Services for Camera is disabled.", eventIds: [], mitre: ["T1430"], commands: [{ label: "Extract GPS EXIF from a photo (if exported)", cmd: "exiftool -gps:all IMG_0001.HEIC" }], related: ["Significant Locations Cache"], retention: "Persists with the photo asset until deleted.", sources: ["ExifTool documentation"] },
  ],
  "Device & System Info": [
    { artifact: "Device Identifiers (UDID, Serial, ICCID)", locations: ["Lockdown properties — accessible via libimobiledevice ideviceinfo, or Settings > General > About"], tools: ["libimobiledevice (ideviceinfo)", "Cellebrite", "AXIOM"], reveals: "UDID, serial number, IMEI/MEID, ICCID, model identifier, iOS version — critical for device identification and chain-of-custody documentation.", eventIds: [], mitre: [], commands: [{ label: "Get device info via libimobiledevice", cmd: "ideviceinfo -u [UDID]" }], related: [], retention: "Hardware identifiers are permanent; software version info changes with each OS update.", sources: ["libimobiledevice project documentation"] },
    { artifact: "Jailbreak Indicators", locations: ["/Applications/Cydia.app", "/private/var/lib/apt/", "/private/var/stash/", "unusual entries in /private/etc/fstab"], tools: ["Manual filesystem inspection", "Cellebrite", "AXIOM"], reveals: "Presence of jailbreak tooling (Cydia, Sileo, apt package manager remnants) — relevant when assessing whether standard iOS security guarantees (sandboxing, code signing) were bypassed on the device.", eventIds: [], mitre: ["T1548"], commands: [], related: ["Device Identifiers (UDID, Serial, ICCID)"], retention: "Persists until the device is restored to a non-jailbroken state via a full OS restore.", sources: ["Public jailbreak community documentation"] },
    { artifact: "MobileInstallation Log", locations: ["/private/var/mobile/Library/Logs/MobileInstallation/mobile_installation.log.0"], tools: ["Cellebrite Physical Analyzer", "Magnet AXIOM", "Text editor"], reveals: "App install/uninstall/update history with timestamps — useful for correlating when a suspicious app first appeared on the device.", eventIds: [], mitre: ["T1406"], commands: [], related: ["Jailbreak Indicators"], retention: "Log rotates by file size/count — typically retains recent weeks of install activity.", sources: ["Apple installation framework documentation"] },
  ],
};
