// IoT & Embedded Device artifact categories — Digital Forensics Reference
// See artifacts/windows.js header for how to add/edit/remove entries.
// NOTE: IoT forensics is highly device-specific — there is no single "IoT OS."
// This file covers the common patterns across embedded Linux (the overwhelming
// majority of consumer IoT), plus companion-app and cloud-side artifacts that
// are often more accessible than the device itself.
export const IoT = {
  "Device Firmware & Storage": [
    { artifact: "Firmware Image (extracted)", locations: ["Obtained via UART/JTAG hardware access, SPI flash chip-off, or vendor firmware update file"], tools: ["binwalk", "Firmware Analysis Toolkit (FAT)", "EMBA", "Ghidra (for binary analysis)"], reveals: "Complete embedded OS image — typically Linux-based (BusyBox userland is extremely common), containing the bootloader, kernel, filesystem, and often hardcoded credentials or debug backdoors left in by the vendor.", eventIds: [], mitre: ["T1542"], commands: [{ label: "Scan firmware image for embedded filesystems", cmd: "binwalk -e firmware.bin" }], related: ["Bootloader & U-Boot Environment"], retention: "Persists in flash storage until the device is reflashed with new firmware — a strong forensic target since it rarely changes without a deliberate update.", sources: ["binwalk project documentation", "EMBA project documentation"] },
    { artifact: "Bootloader & U-Boot Environment", locations: ["Dedicated flash partition, extracted alongside the firmware image"], tools: ["binwalk", "U-Boot tools (fw_printenv)", "JTAG debugger access"], reveals: "Boot configuration and environment variables — can reveal debug console access, serial console credentials, or boot argument tampering used for persistence.", eventIds: [], mitre: ["T1542.005"], commands: [], related: ["Firmware Image (extracted)"], retention: "Persists in dedicated flash storage, generally more durable than the main filesystem since it's rarely rewritten.", sources: ["U-Boot project documentation"] },
    { artifact: "Persistent Configuration Storage (NVRAM/flash)", locations: ["Device-specific flash partition — commonly /dev/mtd* on embedded Linux devices"], tools: ["binwalk", "mtd-utils", "Direct flash chip read (chip-off)"], reveals: "Device settings, paired accounts, Wi-Fi credentials, and often factory-reset-surviving configuration depending on device design.", eventIds: [], mitre: ["T1542.001"], commands: [], related: ["Firmware Image (extracted)"], retention: "Some NVRAM regions survive factory reset by design (to preserve activation state) — check device-specific documentation for what actually gets wiped.", sources: ["mtd-utils project documentation"] },
  ],
  "Network & Companion App": [
    { artifact: "Companion Mobile App Local Data", locations: ["Android: /data/data/[iot-vendor-package]/ ; iOS: app sandbox container"], tools: ["Same mobile forensic tools as standard Android/iOS artifacts (ADB, Cellebrite, AXIOM)"], reveals: "Often the richest accessible artifact for consumer IoT — device pairing history, event logs (e.g., doorbell camera motion events), cached video thumbnails, account credentials, device firmware version history as tracked by the app.", eventIds: [], mitre: ["T1005"], commands: [], related: ["Cloud Vendor Account & Event History"], retention: "Follows the same retention behavior as the underlying mobile OS/app data — see the corresponding Android or iOS artifact entries for detail.", sources: ["Same as standard Android/iOS forensic references"] },
    { artifact: "Cloud Vendor Account & Event History", locations: ["Vendor's own cloud service (e.g., a camera vendor's event/clip history) — accessed via the vendor's API or legal process, not the device itself"], tools: ["Vendor API access (with account credentials or legal request)", "Vendor's own export/download features"], reveals: "For cloud-connected IoT (cameras, doorbells, smart locks), the vendor's cloud often retains far more history than the device's own limited local storage — event timestamps, clip/photo history, access logs.", eventIds: [], mitre: ["T1213"], commands: [], related: ["Companion Mobile App Local Data"], retention: "Varies enormously by vendor and subscription tier — many vendors only retain free-tier event history for a very short window (24-72 hours is common) unless a paid cloud storage plan is active.", sources: ["Vendor-specific documentation (varies by manufacturer)"] },
    { artifact: "Device Network Traffic Capture (live)", locations: ["Captured via a network tap, spanned switch port, or dedicated IoT VLAN monitoring — not stored on the device itself"], tools: ["Wireshark", "tcpdump", "Zeek (network security monitor)"], reveals: "Live network behavior of an IoT device — which cloud endpoints it communicates with, plaintext protocols in use, unexpected outbound connections indicating compromise. Often the only viable evidence source for devices with no accessible local storage.", eventIds: [], mitre: ["T1040", "T1071"], commands: [{ label: "Capture traffic for a specific device IP", cmd: "tcpdump -i eth0 host [device-ip] -w iot_capture.pcap" }], related: ["Cloud Vendor Account & Event History"], retention: "Not retained by the device at all — must be captured live and in real time; there is no after-the-fact recovery once traffic has passed.", sources: ["Wireshark project documentation"] },
  ],
  "Device Identifiers & Provisioning": [
    { artifact: "Device Serial / MAC Address / Hardware ID", locations: ["Physical device label", "Bootloader environment variables", "Vendor cloud account device list"], tools: ["Physical inspection", "U-Boot environment tools", "Vendor account portal"], reveals: "Unique hardware identifiers used to correlate a physical device to its cloud account and network activity — foundational for establishing which device generated a given log entry.", eventIds: [], mitre: [], commands: [], related: ["Bootloader & U-Boot Environment"], retention: "Hardware identifiers are permanent and immutable for the life of the device.", sources: [] },
    { artifact: "Provisioning / Pairing QR or Token History", locations: ["Companion app local storage", "Vendor cloud account activity log"], tools: ["Mobile forensic tools on the companion app", "Vendor API/account access"], reveals: "When and to which account a device was originally paired/provisioned — useful for establishing ownership timeline, especially relevant for secondhand or disputed-ownership devices.", eventIds: [], mitre: [], commands: [], related: ["Companion Mobile App Local Data"], retention: "Persists in the vendor's cloud account history typically for the life of the account; local app cache retention is much shorter and app-dependent.", sources: [] },
  ],
};
